// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB1jMeAFPVNU9cwMvUSWmLmOjxW8OcenAk',
//     appId: '1:781564930131:web:794af72f8d34a4a9527ea6',
//     messagingSenderId: '781564930131',
//     projectId: 'task1-2202f',
//     authDomain: 'task1-2202f.firebaseapp.com',
//     storageBucket: 'task1-2202f.firebasestorage.app',
//     measurementId: 'G-HZC7VNW4J6',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDeoisA3gEnCvzj-IarnAP9-XftS5UDbns',
//     appId: '1:781564930131:android:9788de17c005cf4e527ea6',
//     messagingSenderId: '781564930131',
//     projectId: 'task1-2202f',
//     storageBucket: 'task1-2202f.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBEdRLGhjltF3MwDRYnItMauL8LYkDfbXw',
//     appId: '1:781564930131:ios:9b038fe981607c09527ea6',
//     messagingSenderId: '781564930131',
//     projectId: 'task1-2202f',
//     storageBucket: 'task1-2202f.firebasestorage.app',
//     iosBundleId: 'com.example.task1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBEdRLGhjltF3MwDRYnItMauL8LYkDfbXw',
//     appId: '1:781564930131:ios:9b038fe981607c09527ea6',
//     messagingSenderId: '781564930131',
//     projectId: 'task1-2202f',
//     storageBucket: 'task1-2202f.firebasestorage.app',
//     iosBundleId: 'com.example.task1',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB1jMeAFPVNU9cwMvUSWmLmOjxW8OcenAk',
//     appId: '1:781564930131:web:fde601f586410348527ea6',
//     messagingSenderId: '781564930131',
//     projectId: 'task1-2202f',
//     authDomain: 'task1-2202f.firebaseapp.com',
//     storageBucket: 'task1-2202f.firebasestorage.app',
//     measurementId: 'G-PFZLTSHBVY',
//   );
// }
